version: "3"
services:
  webscrapper:
    image: seblrd/webscrapper
    ports:
      - 81:80
    volumes:
      - ./:/usr/share/nginx/html
    networks:
      network_ws:
        aliases:
          - webscrapper.local

networks:
  network_ws:
    driver: bridge
