version: "3.1"
services:
    ws-db:
        image: mariadb:10.3
        restart: always
        volumes:
            - ./databases:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: password

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8080:80
        expose:
            - 81
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=db
            - VIRTUAL_HOST=phpadmin.reader.local
        depends_on:
            - ws-db

    ws-laravel:
        image: docker.io/bitnami/laravel:9
        ports:
            - 8000:8000
        expose:
            - 82
        environment:
            - DB_HOST=mariadb
            - DB_PORT=3306
            - DB_USERNAME=root
            - DB_DATABASE=webscrapper

            - VIRTUAL_HOST=reader.local
        volumes:
            - './laravel-app:/app'
        depends_on:
            - ws-db
networks:
    default:
        external:
            name: reverse-proxy
