version: "3.1"
services:
    webscrapper:
        image: seblrd/webscrapper
        expose:
            - 80
        volumes:
            - ./:/usr/share/nginx/html
        environment:
            - VIRTUAL_HOST=test.reader.com
    db:
        image: mariadb:10.3
        # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
        # (this is just an example, not intended to be a production configuration)
        # command: --default-authentication-plugin=mysql_native_password
        restart: always
        volumes:
            - ./databases:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: password

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8080:80
        expose:
            - 81
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=db
            - VIRTUAL_HOST=test.phpadmin.reader.com
networks:
    default:
        external:
            name: reverse-proxy
