version: "3"
services:
  webscrapper:
    image: seblrd/webscrapper
    expose:
      - 8002
    volumes:
      - ./:/usr/share/nginx/html
    environment:
      - VIRTUAL_HOST=test.webscrapper.com

  webscrapper-python:
    image: python:3.8.13
    volumes:
      - ./python:/app

networks:
  default:
    external:
      name: nginx-proxy
