version: "3"
services:
  webscrapper-python:
    container_name: webscrapper-python
    image: seblrd/webscrap_python
    volumes:
      - ./:/app
    network_mode: bridge
    depends_on:
      - selenium-firefox

  selenium-firefox:
    container_name: selenium-firefox
    image: selenium/standalone-chrome:4.2.2-20220609
    network_mode: bridge
    ports:
      - "4444:4444"
    restart: unless-stopped
